version: '3.8'

services:
  calculator:
    build: .
    ports:
      - "3000:3000"
    container_name: calculator-microservice
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

networks:
  app-network:
    driver: bridge